name: "Tox Tests"

on:
  push:
    branches: ['!main']

jobs:
  test:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Test
      run: docker-compose -f docker-compose.test.yml up --build
